name: Fluent linter  / Testing Includes

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
          
      - uses: calyptia/fluent-linter-action@gg/adding-parsing-errors-as-annotations
        with:
          CALYPTIA_API_KEY: ${{ secrets.CALYPTIA_API_KEY }}
          CONFIG_LOCATION_GLOB: 'examples/missing-include/fluent-bit-simple.conf'
